#!/bin/sh

sed -i "s|\"API_URL\":.*|\"API_URL\":\"${API_URL:=http://localhost:3005}\"|"  ${CONF_PATH:=/usr/share/www/config.json}

echo "Starting nginx... Egeo Starter should running on port 8080"

nginx

echo "Pulling log"
tail -f  /var/log/nginx/access.log
